name: Build Go

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    #- name: Setup golang version
    #  uses: actions/setup-go@v2
    #  with:
    #    go-version: '1.16.5'
    - name: run
      uses: cedrickring/golang-action@1.6.0
    - name: Debug
      #env:
      #  GOROOT: /opt/hostedtoolcache/go/1.16.5/x64
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
