name: Build v2ray

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      v2raydir: ./v2ray
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: test
      run: |
        echo "${{env.v2raydir}}"
