name: Build Go

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Build xray for padavan'
        required: true
        default: 'build'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup golang version
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.2'

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
